# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_domo',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/nbdev_domo',
                'lib_path': 'nbdev_domo'},
  'syms': {'nbdev_domo.core': {'nbdev_domo.core.foo': ('core.html#foo', 'nbdev_domo/core.py')}}}
