# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_domo',
                'doc_host': 'https://jaewilson07.github.io',
                'git_url': 'https://github.com/jaewilson07/nbdev_domo',
                'lib_path': 'nbdev_domo'},
  'syms': { 'nbdev_domo.ResponseGetData': { 'nbdev_domo.ResponseGetData.ResponseGetData': ( 'responsegetdata.html#responsegetdata',
                                                                                            'nbdev_domo/ResponseGetData.py'),
                                            'nbdev_domo.ResponseGetData.ResponseGetData._from_aiohttp_response': ( 'responsegetdata.html#responsegetdata._from_aiohttp_response',
                                                                                                                   'nbdev_domo/ResponseGetData.py'),
                                            'nbdev_domo.ResponseGetData.ResponseGetData._from_requests_response': ( 'responsegetdata.html#responsegetdata._from_requests_response',
                                                                                                                    'nbdev_domo/ResponseGetData.py')},
            'nbdev_domo.core': {'nbdev_domo.core.foo': ('core.html#foo', 'nbdev_domo/core.py')}}}
