# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_Utils.ipynb.

# %% auto 0
__all__ = ['DictDot']

# %% ../nbs/99_Utils.ipynb 3
from types import SimpleNamespace


# %% ../nbs/99_Utils.ipynb 4
class DictDot(SimpleNamespace):
    """convenience class that converts dictionaries to objects with attributes that can be accessed with dot notation."""

    def __init__(self,
                 dictionary,
                 **kwargs):
        super().__init__(**kwargs)

        for key, value in dictionary.items():
            if isinstance(value, dict):
                self.__setattr__(key, DictDot(value))
            elif isinstance(value, list):
                new_list = []
                for item in value:
                    if isinstance(item, dict):
                        new_list.append(DictDot(item))
                    else:
                        new_list.append(item)
                self.__setattr__(key, new_list)
            else:
                self.__setattr__(key, value)

    def __getattr__(self, item):
        return None

